# Generated by Django 6.0.1 on 2026-02-23 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealTrain', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealtrain',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='mealtrain',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='mealtrain',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='mealtrain',
            name='restrictions',
        ),
        migrations.RemoveField(
            model_name='mealtrain',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='mealtrain',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='mealtrain',
            name='beneficiary_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mealtrain',
            name='beneficiary_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mealtrain',
            name='beneficiary_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealtrain',
            name='beneficiary_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mealtrain',
            name='dietary_restrictions',
            field=models.TextField(blank=True, help_text='General dietary notes for the beneficiary', null=True),
        ),
        migrations.AddField(
            model_name='mealtrain',
            name='organizer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='organized_meal_trains', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mealtrain',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mealtrain',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='MealSlot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slot_date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20)),
                ('meal_train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='mealTrain.mealtrain')),
            ],
            options={
                'ordering': ['slot_date', 'meal_type'],
                'unique_together': {('meal_train', 'slot_date', 'meal_type')},
            },
        ),
        migrations.CreateModel(
            name='MealSignup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('meal_description', models.CharField(blank=True, help_text='What the participant plans to bring/serve', max_length=500, null=True)),
                ('special_notes', models.TextField(blank=True, help_text='Any special notes for this signup', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_signups', to=settings.AUTH_USER_MODEL)),
                ('meal_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='mealTrain.mealslot')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealTrainMembership',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('meal_train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='mealTrain.mealtrain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_train_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.DeleteModel(
            name='MealTrainParticipant',
        ),
        migrations.AddConstraint(
            model_name='mealsignup',
            constraint=models.UniqueConstraint(fields=('meal_slot', 'participant'), name='unique_meal_slot_participant'),
        ),
        migrations.AlterUniqueTogether(
            name='mealtrainmembership',
            unique_together={('user', 'meal_train')},
        ),
    ]
